create table if not exists public.vocabulary (
  id bigint generated by default as identity primary key,
  word text not null,
  definition text not null,
  example text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.mcq_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  option_a text not null default '',
  option_b text not null default '',
  option_c text not null default '',
  option_d text not null default '',
  mode text not null default 'general',
  answer text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.matching_questions (
  id bigint generated by default as identity primary key,
  word text not null,
  meaning text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.fill_blank_questions (
  id bigint generated by default as identity primary key,
  sentence text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.writing_questions (
  id bigint generated by default as identity primary key,
  word text not null,
  hint text not null,
  keywords jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.listing_questions (
  id bigint generated by default as identity primary key,
  prompt text not null,
  hint text not null default '',
  answers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
