create table if not exists public.vocabulary (
  id bigint generated by default as identity primary key,
  word text not null,
  definition text not null,
  example text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.mcq_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  option_a text not null default '',
  option_b text not null default '',
  option_c text not null default '',
  option_d text not null default '',
  mode text not null default 'general',
  answer text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.matching_questions (
  id bigint generated by default as identity primary key,
  word text not null,
  meaning text not null,
  created_at timestamptz not null default now()
);

create index if not exists matching_questions_word_idx
  on public.matching_questions (word);

create table if not exists public.fill_blank_questions (
  id bigint generated by default as identity primary key,
  sentence text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.writing_questions (
  id bigint generated by default as identity primary key,
  word text not null,
  hint text not null,
  keywords jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table if exists public.writing_questions
  add column if not exists kind text not null default 'writing';

-- Migrate legacy listing table into writing_questions (shared table design).
do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'listing_questions'
  ) then
    insert into public.writing_questions (word, hint, keywords, kind)
    select
      l.prompt,
      l.hint,
      l.answers,
      'listing'
    from public.listing_questions l
    where not exists (
      select 1
      from public.writing_questions w
      where w.kind = 'listing'
        and w.word = l.prompt
        and w.hint = l.hint
        and w.keywords = l.answers
    );
  end if;
end
$$;
