-- Supabase schema for learnEnglish.
-- Safe to run more than once in the Supabase SQL Editor.

create table if not exists public.vocabulary (
  id bigint generated by default as identity primary key,
  word text not null,
  definition text not null,
  example text not null default '',
  word_type text not null default 'other',
  mastered_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table if exists public.vocabulary
  add column if not exists example text not null default '';
alter table if exists public.vocabulary
  add column if not exists word_type text not null default 'other';
alter table if exists public.vocabulary
  add column if not exists mastered_count integer not null default 0;
alter table if exists public.vocabulary
  add column if not exists created_at timestamptz not null default now();

update public.vocabulary
set
  example = coalesce(example, ''),
  word_type = case
    when word_type in ('noun', 'verb', 'adjective', 'other') then word_type
    else 'other'
  end,
  mastered_count = greatest(coalesce(mastered_count, 0), 0);

create table if not exists public.mcq_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  option_a text not null default '',
  option_b text not null default '',
  option_c text not null default '',
  option_d text not null default '',
  mode text not null default 'general',
  answer text not null,
  created_at timestamptz not null default now()
);

alter table if exists public.mcq_questions
  add column if not exists option_a text not null default '';
alter table if exists public.mcq_questions
  add column if not exists option_b text not null default '';
alter table if exists public.mcq_questions
  add column if not exists option_c text not null default '';
alter table if exists public.mcq_questions
  add column if not exists option_d text not null default '';
alter table if exists public.mcq_questions
  add column if not exists mode text not null default 'general';
alter table if exists public.mcq_questions
  add column if not exists created_at timestamptz not null default now();

update public.mcq_questions
set
  option_a = coalesce(option_a, ''),
  option_b = coalesce(option_b, ''),
  option_c = coalesce(option_c, ''),
  option_d = coalesce(option_d, ''),
  mode = case
    when mode in ('general', 'vocabulary_definition') then mode
    else 'general'
  end;

create table if not exists public.matching_questions (
  id bigint generated by default as identity primary key,
  word text not null,
  meaning text not null,
  created_at timestamptz not null default now()
);

alter table if exists public.matching_questions
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.fill_blank_questions (
  id bigint generated by default as identity primary key,
  sentence text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

alter table if exists public.fill_blank_questions
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.writing_questions (
  id bigint generated by default as identity primary key,
  word text not null,
  hint text not null default '',
  keywords jsonb not null default '[]'::jsonb,
  answer text not null default '',
  kind text not null default 'writing',
  created_at timestamptz not null default now()
);

alter table if exists public.writing_questions
  add column if not exists hint text not null default '';
alter table if exists public.writing_questions
  add column if not exists keywords jsonb not null default '[]'::jsonb;
alter table if exists public.writing_questions
  add column if not exists answer text not null default '';
alter table if exists public.writing_questions
  add column if not exists kind text not null default 'writing';
alter table if exists public.writing_questions
  add column if not exists created_at timestamptz not null default now();

update public.writing_questions
set
  hint = coalesce(hint, ''),
  keywords = case
    when keywords is null then '[]'::jsonb
    when jsonb_typeof(keywords) = 'array' then keywords
    else '[]'::jsonb
  end,
  answer = coalesce(answer, ''),
  kind = case
    when kind in ('writing', 'listing', 'arrange') then kind
    else 'writing'
  end;

-- Legacy migration: old listing_questions rows now live in writing_questions
-- with kind = 'listing'.
do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'listing_questions'
  ) then
    insert into public.writing_questions (word, hint, keywords, answer, kind)
    select
      l.prompt,
      coalesce(l.hint, ''),
      case
        when jsonb_typeof(l.answers) = 'array' then l.answers
        else '[]'::jsonb
      end,
      '',
      'listing'
    from public.listing_questions l
    where not exists (
      select 1
      from public.writing_questions w
      where w.kind = 'listing'
        and w.word = l.prompt
        and w.hint = coalesce(l.hint, '')
    );
  end if;
end
$$;

-- Arrange questions previously stored the correct sentence as the first
-- keyword. Keep that data usable after the answer column was introduced.
update public.writing_questions
set answer = keywords ->> 0
where kind = 'arrange'
  and coalesce(answer, '') = ''
  and jsonb_typeof(keywords) = 'array'
  and jsonb_array_length(keywords) > 0;

create index if not exists vocabulary_word_idx
  on public.vocabulary (word);
create index if not exists vocabulary_word_type_idx
  on public.vocabulary (word_type);

create index if not exists mcq_questions_mode_idx
  on public.mcq_questions (mode);

create index if not exists matching_questions_word_idx
  on public.matching_questions (word);

create index if not exists fill_blank_questions_answer_idx
  on public.fill_blank_questions (answer);

create index if not exists writing_questions_kind_idx
  on public.writing_questions (kind);
create index if not exists writing_questions_word_idx
  on public.writing_questions (word);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'vocabulary_word_type_check'
  ) then
    alter table public.vocabulary
      add constraint vocabulary_word_type_check
      check (word_type in ('noun', 'verb', 'adjective', 'other'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'vocabulary_mastered_count_check'
  ) then
    alter table public.vocabulary
      add constraint vocabulary_mastered_count_check
      check (mastered_count >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'mcq_questions_mode_check'
  ) then
    alter table public.mcq_questions
      add constraint mcq_questions_mode_check
      check (mode in ('general', 'vocabulary_definition'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'writing_questions_kind_check'
  ) then
    alter table public.writing_questions
      add constraint writing_questions_kind_check
      check (kind in ('writing', 'listing', 'arrange'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'writing_questions_keywords_array_check'
  ) then
    alter table public.writing_questions
      add constraint writing_questions_keywords_array_check
      check (jsonb_typeof(keywords) = 'array');
  end if;
end
$$;
